apiVersion: v1
kind: Service
metadata:
  name: fipbhphgaa # service name
spec:
  type: NodePort
  ports:
  - port: 6666 # port on cluster (clusterIP:port)
    nodePort: 30000 # port on node (nodeIP:port)
    protocol: TCP
    targetPort: 8080 # port on container
  selector:
    app: fipbhphgaa # deployment name